name: Stage

on:
  push:
    branches: 
      - 'v*'

jobs:
  Build:
    uses: ./.github/workflows/build.yml
    
  Scan:
    uses: ./.github/workflows/scan.yml
    permissions:
      contents: read
      actions: read
      security-events: write

